services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - port=8000
    env_file: .env
    ports:
      - 8000:8000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
