services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
        #    - port=8000 TODO: cmd from shell script, script reads port no
    container_name: api
    environment:
     BOT_TOKEN: ${BOT_TOKEN}
     LAMBDA_URL: ${LAMBDA_URL}
     HOST: ${HOST}
    networks:
      - aws
    volumes:
      - users:/opt/users
      - ./api/src:/app/src

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST: ${HOST}
    networks:
      - aws
    depends_on:
      - api

networks:
  aws:
    name: aws
    driver: bridge
    attachable: true

volumes:
  users:
