services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
     BOT_TOKEN: ${BOT_TOKEN}
     LAMBDA_URL: ${LAMBDA_URL}
     HOST: ${HOST}
     ADMIN: ${ADMIN}
     TEST_USER: ${TEST_USER}
    networks:
      - aws
    volumes:
      - users:/opt/users
      - ./api/src:/app/src
    restart: unless-stopped

  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST: ${HOST}
    networks:
      - aws
    depends_on:
      - api
    restart: unless-stopped

networks:
  aws:
    name: aws
    driver: bridge
    attachable: true

volumes:
  users:
