services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
     BOT_TOKEN: ${BOT_TOKEN}
     LAMBDA_URL: ${LAMBDA_URL}
     HOST: ${HOST}
     ADMIN: ${ADMIN}
     TEST_USER: ${TEST_USER}
    networks:
      - aws
    volumes:
      - /app/db
      - ./api/src:/app/src
    depends_on:
      - nginx
    restart: unless-stopped
    #command: tail -f /dev/null

  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST: ${HOST}
    networks:
      - aws
        # fastapi should start first <= setWebhook needs working domain
        # nginx should start first <= it resolves to fastapi
    restart: unless-stopped
    #command: tail -f /dev/null

networks:
  aws:
    name: aws
    driver: bridge
    attachable: true

