services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
        #    - port=8000 TODO: cmd from shell script, script reads port no
    container_name: api
    env_file: .env
    networks:
      - aws
    depends_on:
      - nginx
  nginx:
    build:
      context: ./nginx
      dockerfile_inline: |
        FROM nginx:latest
        RUN apt update && apt install -y vim iputils-ping
    ports:
      - "80:80"
    container_name: nginx
    networks:
      - aws
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    

networks:
  aws:
    name: aws
    driver: bridge
    attachable: true
